[project]
name = "09-llm-project-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "openai>=1.107.0",
    "python-dotenv>=1.1.1",
]
